### ISSUE TITLE
Measuring positive / negative power

### ISSUE THREAD

**Issue by petit-miner** [ecsfang/3phase_meter#1]
Hi there,
I just have one question about the source code / measurement setup, can it measure positive and negative power?
I'm currently exporting power into the grid and I would like to measure that aswell.

**Comment by ecsfang** [comment]
Hi,
No, this simple solution only measure the absolute value of the current in the line that has the clamp on it.
Don't know how to measure the direction of the current flow ...

**Comment by petit-miner** [comment]
Thanks!
